merchantNames = ["Swap-O-Matic", "Gobber Muncher", "Weathered Salesperson", "Grass Illager", "Evil Oversized Turtle"]
feedingTroughRange = 8
feedingTroughMaxAnimals = 8
chickenNestRange = 8
fertilizerBonusCropChance = 1.0
fertilizerBonusGrowthChance = 1.0
fertilizerRegressionChance = 0.0
showRegistryWarnings = false
